const configData: IAppList = [
  {
    package_name: "com.dts.freefireth.huawei",
    cloud_supported: false,
    selected_game: true,
    size: "0.0B",
    platform_name: "Garena International",
    selected_game_order: 47,
    sort_rank: 1010.1929208857833,
    icon_url:
      "https://cdn-bgp.bluestacks.com/BGP/in/icon_com.dts.freefireth.huawei.jpg",
    section: "ApkInstallation",
    app_center_id: 340343,
    download_url:
      "https://cdn-bgp.bluestacks.com/BGP/us/apk/com.dts.freefireth.huawei.apk",
    source: "android",
    version: "None",
    downloadqrcode_url:
      "https://cdn-bgp.bluestacks.com/BGP/us/qrcode_com.dts.freefireth.huawei.jpg",
    type: ["Action"],
    status: 1,
    game_play_preference: ["local"],
    modify_date: "2021-11-08",
    tags: ["Free Fire (Huawei) "],
    pinyin: "None",
    dau: 1059,
    selected_game_sticky: false,
    platform_zh_name: "Garena International",
    download_count: 1000,
    icon_tag: null,
    is_nowgg_login_required: false,
    apk_url:
      "https://cdn3.bluestacks.com/bluestacks-app-store/Internal/com.dts.freefireth.huawei/1.90.1/com.dts.freefireth.huawei.apk",
    cloud_app_url: null,
    game_name_lower: "free fire (huawei version)",
    level: 0,
    screenshots_type: "heng",
    instruction: "",
    app_ver_modify_date: "2021-11-02 20:17:29",
    game_name: "Free Fire (Huawei Version)",
    initails_pinyin: "None",
    small_icon_url:
      "https://cdn-bgp.bluestacks.com/BGP/us/icon_freefire.apk.jpg",
    action: "InstallCDN",
  },
  {
    package_name: "com.mobilityware.freecell",
    cloud_supported: false,
    size: "0.0B",
    platform_name: "MobilityWare",
    sort_rank: 4.179339196381232,
    icon_url:
      "https://cdn-icon.bluestacks.com/InR1A4hkkmeA6Y7fKx8WQR6HtVQUxpxfswVuQpMgBoqmFavqyXdIW8_edZShVj18GfI=w368",
    app_center_id: 1660,
    download_url:
      "https://play.google.com/store/apps/details?id=com.mobilityware.freecell",
    source: "android",
    version: "Varies with device",
    downloadqrcode_url:
      "https://cdn-bgp.bluestacks.com/BGP/Us/qrcode_com.mobilityware.freecell.jpg",
    type: ["Card"],
    status: 1,
    game_play_preference: ["local"],
    modify_date: "2022-05-23",
    tags: [],
    pinyin: null,
    dau: 73,
    platform_zh_name: "MobilityWare",
    download_count: 1000,
    icon_tag: null,
    is_nowgg_login_required: false,
    cloud_app_url: null,
    game_name_lower: "freecell solitaire: card games",
    level: 8,
    tag_order: 763,
    screenshots_type: "shu",
    instruction: "",
    app_ver_modify_date: "2017-08-23 06:58:34",
    game_name: "FreeCell Solitaire: Card Games",
    initails_pinyin: null,
    small_icon_url:
      "https://cdn-icon.bluestacks.com/InR1A4hkkmeA6Y7fKx8WQR6HtVQUxpxfswVuQpMgBoqmFavqyXdIW8_edZShVj18GfI=w88",
  },
  {
    package_name: "com.forsbit.freecell",
    cloud_supported: false,
    size: "0.0B",
    platform_name: "Forsbit LLC",
    sort_rank: 2.0,
    icon_url:
      "https://cdn-icon.bluestacks.com/mPARPVOl3iPL3_TsNX1P7t16tzWkreUCQLgzAreYvf0a_vsShhfF4z-ReMZNHh4k61_X=w368",
    app_center_id: 68527,
    download_url:
      "https://play.google.com/store/apps/details?id=com.forsbit.freecell",
    source: "android",
    version: "1.0.3",
    downloadqrcode_url:
      "https://cdn-bgp.bluestacks.com/BGP/us/qrcode_com.forsbit.freecell.jpg",
    type: ["Card"],
    status: 1,
    game_play_preference: ["local"],
    modify_date: "2022-05-23",
    tags: [],
    pinyin: null,
    dau: 8,
    platform_zh_name: "Forsbit LLC",
    download_count: 1000,
    icon_tag: null,
    is_nowgg_login_required: false,
    cloud_app_url: null,
    game_name_lower: "freecell solitaire classic  free cell card game",
    level: 10,
    screenshots_type: "shu",
    instruction: "",
    app_ver_modify_date: "2017-12-18 22:23:38",
    game_name: "FreeCell Solitaire Classic  free cell card game",
    initails_pinyin: null,
    small_icon_url:
      "https://cdn-icon.bluestacks.com/mPARPVOl3iPL3_TsNX1P7t16tzWkreUCQLgzAreYvf0a_vsShhfF4z-ReMZNHh4k61_X=w88",
  },
  {
    package_name: "com.staplegames.freecellSolitaireGP",
    cloud_supported: false,
    size: "0.0B",
    platform_name: "Staple Games",
    sort_rank: 1.912931182772389,
    icon_url:
      "https://cdn-icon.bluestacks.com/JeRZQn0qzsBz1rp06b4_ank25vIpcqIdtmf259KDjftXnbrBQWtmU1P9Elp0Lwqu88Cq=w368",
    app_center_id: 334021,
    download_url:
      "https://play.google.com/store/apps/details?id=com.staplegames.freecellSolitaireGP",
    source: "android",
    version: "1.33",
    downloadqrcode_url:
      "https://cdn-bgp.bluestacks.com/BGP/us/qrcode_com.staplegames.freecellSolitaireGP.jpg",
    type: ["Card"],
    status: 1,
    game_play_preference: ["local"],
    modify_date: "2022-05-23",
    tags: [],
    pinyin: null,
    dau: 7,
    platform_zh_name: "Staple Games",
    download_count: 1000,
    icon_tag: null,
    is_nowgg_login_required: false,
    cloud_app_url: null,
    game_name_lower: "freecell (classic card game)",
    level: 10,
    screenshots_type: "shu",
    instruction: "",
    app_ver_modify_date: "2021-10-12 04:58:03",
    game_name: "FreeCell (Classic Card Game)",
    initails_pinyin: null,
    small_icon_url:
      "https://cdn-icon.bluestacks.com/JeRZQn0qzsBz1rp06b4_ank25vIpcqIdtmf259KDjftXnbrBQWtmU1P9Elp0Lwqu88Cq=w88",
  },
  {
    package_name: "com.karmangames.freecell",
    cloud_supported: false,
    size: "0.0B",
    platform_name: "KARMAN Games",
    sort_rank: 1.7099759466766968,
    icon_url:
      "https://cdn-icon.bluestacks.com/S27BbOog__1FQEWKbmsBN1xvZ3Hr0x8sNAFdxODwlqunZHSLiE-s399AwdUgYMV2=w368",
    app_center_id: 117709,
    download_url:
      "https://play.google.com/store/apps/details?id=com.karmangames.freecell",
    source: "android",
    version: "Varies with device",
    downloadqrcode_url:
      "https://cdn-bgp.bluestacks.com/BGP/us/qrcode_com.karmangames.freecell.jpg",
    type: ["Card"],
    status: 1,
    game_play_preference: ["local"],
    modify_date: "2022-05-23",
    tags: [],
    pinyin: null,
    dau: 5,
    platform_zh_name: "KARMAN Games",
    download_count: 1000,
    icon_tag: null,
    is_nowgg_login_required: false,
    cloud_app_url: null,
    game_name_lower: "freecell",
    level: 10,
    screenshots_type: "shu",
    instruction: "",
    app_ver_modify_date: "2018-06-13 16:38:21",
    game_name: "FreeCell",
    initails_pinyin: null,
    small_icon_url:
      "https://cdn-icon.bluestacks.com/S27BbOog__1FQEWKbmsBN1xvZ3Hr0x8sNAFdxODwlqunZHSLiE-s399AwdUgYMV2=w88",
  },
  {
    package_name: "com.cardgame.freecell.fishdom",
    cloud_supported: false,
    size: "0.0B",
    platform_name: "Solitaire Fun",
    sort_rank: 1.4422495703074083,
    icon_url:
      "https://cdn-icon.bluestacks.com/-JZm4NUx0lblqooRSXnu6jMWBXdf0SFem6QpJOBWE2L5ZVvO2cX_jbdxvG01nxrDLA=w368",
    app_center_id: 105630,
    download_url:
      "https://play.google.com/store/apps/details?id=com.cardgame.freecell.fishdom",
    source: "android",
    version: "2.9.477",
    downloadqrcode_url:
      "https://cdn-bgp.bluestacks.com/BGP/us/qrcode_com.cardgame.freecell.fishdom.jpg",
    type: ["Card"],
    status: 1,
    game_play_preference: ["local"],
    modify_date: "2022-05-23",
    tags: [],
    pinyin: null,
    dau: 3,
    platform_zh_name: "Solitaire Fun",
    download_count: 1000,
    icon_tag: null,
    is_nowgg_login_required: false,
    cloud_app_url: null,
    game_name_lower: "freecell solitaire",
    level: 10,
    screenshots_type: "shu",
    instruction: "",
    app_ver_modify_date: "2018-05-14 16:08:56",
    game_name: "FreeCell Solitaire",
    initails_pinyin: null,
    small_icon_url:
      "https://cdn-icon.bluestacks.com/-JZm4NUx0lblqooRSXnu6jMWBXdf0SFem6QpJOBWE2L5ZVvO2cX_jbdxvG01nxrDLA=w88",
  },
  {
    package_name: "com.free.solitaire.games",
    cloud_supported: false,
    size: "0.0B",
    platform_name: "Free Solitaire",
    sort_rank: 1.0,
    icon_url:
      "https://cdn-icon.bluestacks.com/9b__unXvWm8vw9hisX-jwDlJsU_sLqe5FhDCO3K9qUA8BnBNioJCcJ0ld-jn9Kwv5PVA=w368",
    app_center_id: 1785,
    download_url:
      "https://play.google.com/store/apps/details?id=com.free.solitaire.games",
    source: "android",
    version: "1.0",
    downloadqrcode_url:
      "https://cdn-bgp.bluestacks.com/BGP/Us/qrcode_com.free.solitaire.games.jpg",
    type: ["Card"],
    status: 1,
    game_play_preference: ["local"],
    modify_date: "2022-05-23",
    tags: [],
    pinyin: null,
    dau: 1,
    platform_zh_name: "Free Solitaire",
    download_count: 1000,
    icon_tag: null,
    is_nowgg_login_required: false,
    cloud_app_url: null,
    game_name_lower: "free solitaire",
    level: 9,
    screenshots_type: "shu",
    instruction: "",
    app_ver_modify_date: "2017-08-23 06:58:34",
    game_name: "Free Solitaire",
    initails_pinyin: null,
    small_icon_url:
      "https://cdn-icon.bluestacks.com/9b__unXvWm8vw9hisX-jwDlJsU_sLqe5FhDCO3K9qUA8BnBNioJCcJ0ld-jn9Kwv5PVA=w88",
  },
  {
    package_name: "com.mintgames.freecell.solitaire",
    cloud_supported: false,
    size: "0.0B",
    platform_name: "Mint Games",
    sort_rank: 1.0,
    icon_url:
      "https://cdn-icon.bluestacks.com/LWtFRg2mJHNqgfMcpiDkflUZAUhSp-14OVS1J4s-eV6c05t60cIh2oIiCUdR9l3EQVWb=w368",
    app_center_id: 348926,
    download_url:
      "https://play.google.com/store/apps/details?id=com.mintgames.freecell.solitaire",
    source: "android",
    version: "1.0.0",
    downloadqrcode_url:
      "https://cdn-bgp.bluestacks.com/BGP/us/qrcode_com.mintgames.freecell.solitaire.jpg",
    type: ["Card"],
    status: 1,
    game_play_preference: ["local"],
    modify_date: "2022-05-23",
    tags: [],
    pinyin: null,
    dau: 1,
    platform_zh_name: "Mint Games",
    download_count: 1000,
    icon_tag: null,
    is_nowgg_login_required: false,
    cloud_app_url: null,
    game_name_lower: "freecell solitaire",
    level: 9,
    screenshots_type: "shu",
    instruction: "",
    app_ver_modify_date: "2021-12-21 06:42:12",
    game_name: "Freecell Solitaire",
    initails_pinyin: null,
    small_icon_url:
      "https://cdn-icon.bluestacks.com/LWtFRg2mJHNqgfMcpiDkflUZAUhSp-14OVS1J4s-eV6c05t60cIh2oIiCUdR9l3EQVWb=w88",
  },
  {
    package_name: "com.lemongame.freecell.solitaire",
    cloud_supported: false,
    size: "0.0B",
    platform_name: "Solitaire Card Games , Inc.",
    sort_rank: 1.0,
    icon_url:
      "https://cdn-icon.bluestacks.com/F4a5lAdk229xtKBvrNB81Gj1SlnxcUcXvjOHMCKIJep9_F3Ma0dYWcBAzkdd3cQc2UOJ=w368",
    app_center_id: 180394,
    download_url:
      "https://play.google.com/store/apps/details?id=com.lemongame.freecell.solitaire",
    source: "android",
    version: "2.4",
    downloadqrcode_url:
      "https://cdn-bgp.bluestacks.com/BGP/us/qrcode_com.lemongame.freecell.solitaire.jpg",
    type: ["Card"],
    status: 1,
    game_play_preference: ["local"],
    modify_date: "2022-05-23",
    tags: [],
    pinyin: null,
    dau: 1,
    platform_zh_name: "Solitaire Card Games , Inc.",
    download_count: 1000,
    icon_tag: null,
    is_nowgg_login_required: false,
    cloud_app_url: null,
    game_name_lower: "freecell solitaire",
    level: 9,
    screenshots_type: "shu",
    instruction: "",
    app_ver_modify_date: "2019-02-25 13:40:40",
    game_name: "FreeCell Solitaire",
    initails_pinyin: null,
    small_icon_url:
      "https://cdn-icon.bluestacks.com/F4a5lAdk229xtKBvrNB81Gj1SlnxcUcXvjOHMCKIJep9_F3Ma0dYWcBAzkdd3cQc2UOJ=w88",
  },
  {
    package_name: "com.bi.slots.casino",
    cloud_supported: false,
    size: "0.0B",
    platform_name: "Bad Ibis Games Ltd",
    sort_rank: 0.0,
    icon_url:
      "https://cdn-icon.bluestacks.com/aeo_lpve4utuJYNaOunw8hjFa6CfpHJPVONqbMujI-yExItSn50lIN2Ki_rg75ds3mg=w368",
    app_center_id: 98753,
    download_url:
      "https://play.google.com/store/apps/details?id=com.bi.slots.casino",
    source: "android",
    version: "1.25.15",
    downloadqrcode_url:
      "https://cdn-bgp.bluestacks.com/BGP/us/qrcode_com.bi.slots.casino.jpg",
    type: ["Board"],
    status: 1,
    game_play_preference: ["local"],
    modify_date: "2022-05-23",
    tags: [],
    pinyin: null,
    dau: 0,
    platform_zh_name: "Bad Ibis Games Ltd",
    download_count: 1000,
    icon_tag: null,
    is_nowgg_login_required: false,
    cloud_app_url: null,
    game_name_lower: "free slots casino royale - new slot machines 2018",
    level: 8,
    screenshots_type: "shu",
    instruction: "",
    app_ver_modify_date: "2018-05-07 16:04:19",
    game_name: "Free Slots Casino Royale - New Slot Machines 2018",
    initails_pinyin: null,
    small_icon_url:
      "https://cdn-icon.bluestacks.com/aeo_lpve4utuJYNaOunw8hjFa6CfpHJPVONqbMujI-yExItSn50lIN2Ki_rg75ds3mg=w88",
  },
  {
    package_name:
      "freecell.solitaire.free.cardgame.king.spades.klondike.no.ads.pro.patience",
    cloud_supported: false,
    size: "0.0B",
    platform_name: "Fantasy Word Games",
    sort_rank: 0.0,
    icon_url:
      "https://cdn-icon.bluestacks.com/UyWYCd6ZyhfHRZj9MQG0dXE6Goaml7sbfG883LzjuZZnrjCisZNZPyWqx_YTcDPvtPs=w368",
    app_center_id: 213723,
    download_url:
      "https://play.google.com/store/apps/details?id=freecell.solitaire.free.cardgame.king.spades.klondike.no.ads.pro.patience",
    source: "android",
    version: "1.0",
    downloadqrcode_url:
      "https://cdn-bgp.bluestacks.com/BGP/us/qrcode_freecell.solitaire.free.cardgame.king.spades.klondike.no.ads.pro.patience.jpg",
    type: ["Card"],
    status: 1,
    game_play_preference: ["local"],
    modify_date: "2022-05-23",
    tags: [],
    pinyin: null,
    dau: 0,
    platform_zh_name: "Fantasy Word Games",
    download_count: 1000,
    icon_tag: null,
    is_nowgg_login_required: false,
    cloud_app_url: null,
    game_name_lower: "freecell solitaire - classic card games",
    level: 8,
    screenshots_type: "shu",
    instruction: "",
    app_ver_modify_date: "2019-07-12 12:14:59",
    game_name: "FreeCell Solitaire - Classic Card Games",
    initails_pinyin: null,
    small_icon_url:
      "https://cdn-icon.bluestacks.com/UyWYCd6ZyhfHRZj9MQG0dXE6Goaml7sbfG883LzjuZZnrjCisZNZPyWqx_YTcDPvtPs=w88",
  },
  {
    package_name: "com.slotsfavorites.slots.android",
    cloud_supported: false,
    size: "0.0B",
    platform_name: "Super Lucky Casino",
    sort_rank: 0.0,
    icon_url:
      "https://cdn-icon.bluestacks.com/dn3Je1kMokSW3efoZJO2fXsf2y8yqfnlSdqnDZ4KEo_9TbZifwzOyEfz1sdxZrLhg8M=w368",
    app_center_id: 20487,
    download_url:
      "https://play.google.com/store/apps/details?id=com.slotsfavorites.slots.android",
    source: "android",
    version: "1.134",
    downloadqrcode_url:
      "https://cdn-bgp.bluestacks.com/BGP/us/qrcode_com.slotsfavorites.slots.android.jpg",
    type: ["Casino"],
    status: 1,
    game_play_preference: ["local"],
    modify_date: "2022-05-23",
    tags: [],
    pinyin: null,
    dau: 0,
    platform_zh_name: "Super Lucky Casino",
    download_count: 1000,
    icon_tag: null,
    is_nowgg_login_required: false,
    cloud_app_url: null,
    game_name_lower: "free slots!",
    level: 10,
    screenshots_type: "shu",
    instruction: "",
    app_ver_modify_date: "2017-08-23 06:58:34",
    game_name: "Free Slots!",
    initails_pinyin: null,
    small_icon_url:
      "https://cdn-icon.bluestacks.com/dn3Je1kMokSW3efoZJO2fXsf2y8yqfnlSdqnDZ4KEo_9TbZifwzOyEfz1sdxZrLhg8M=w88",
  },
  {
    publisher: ["Warner Bros. Interactive Entertainment"],
    is_early_access: false,
    app_name: "Gotham City Impostors Free to Play",
    steam_id: "206210",
    vr_support: "not_supported",
    all_review_count: 11640,
    source: "steam",
    supported_os: ["win"],
    genre: ["Action", "Free to Play"],
    score: 0.6,
    img_url:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/206210/header.jpg?t=1461103628",
    release_date: "2012-08-30",
    developer: null,
  },
  {
    publisher: null,
    is_early_access: false,
    app_name: "The Way of Life Free Edition",
    steam_id: "310370",
    vr_support: "not_supported",
    all_review_count: 6664,
    source: "steam",
    supported_os: ["win", "mac", "linux"],
    genre: ["Free to Play", "Indie"],
    score: 0.625,
    img_url:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/310370/header.jpg?t=1526650783",
    release_date: "2016-05-31",
    developer: ["Fabio Ferrara"],
  },
  {
    publisher: ["Square Enix"],
    is_early_access: false,
    app_name: "DISSIDIA FINAL FANTASY NT Free Edition",
    steam_id: "921590",
    vr_support: "not_supported",
    all_review_count: 2883,
    source: "steam",
    supported_os: ["win"],
    genre: ["Action", "Free to Play"],
    score: 0.5833333333333334,
    img_url:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/921590/header.jpg?t=1583341768",
    release_date: "2019-03-12",
    developer: ["Square Enix", "KOEI TECMO GAMES CO., LTD."],
  },
  {
    publisher: ["Movie Games S.A.", "PlayWay S.A."],
    is_early_access: false,
    app_name: "Drug Dealer Simulator: Free Sample",
    steam_id: "1275630",
    vr_support: "not_supported",
    all_review_count: 2329,
    source: "steam",
    supported_os: ["win"],
    genre: ["Action", "Casual", "Free to Play", "Indie", "Simulation"],
    score: 0.6,
    img_url:
      "https://cdn.akamai.steamstatic.com/steam/apps/1275630/header.jpg?t=1616763198",
    release_date: "2020-04-03",
    developer: ["Byterunners Game Studio"],
  },
  {
    publisher: ["Monkeys Lab."],
    is_early_access: false,
    app_name: "Fog Of War - Free Edition",
    steam_id: "691020",
    vr_support: "not_supported",
    all_review_count: 1679,
    source: "steam",
    supported_os: ["win"],
    genre: ["Action", "Free to Play", "Indie", "Massively Multiplayer"],
    score: 0.625,
    img_url:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/691020/header.jpg?t=1519307727",
    release_date: "2018-02-22",
    developer: ["Monkeys Lab."],
  },
  {
    publisher: null,
    is_early_access: false,
    app_name: "The Backrooms Game FREE Edition",
    steam_id: "1111210",
    vr_support: "not_supported",
    all_review_count: 1406,
    source: "steam",
    supported_os: ["win", "linux"],
    genre: ["Adventure", "Casual", "Free to Play", "Indie", "Simulation"],
    score: 0.625,
    img_url:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1111210/header.jpg?t=1568759565",
    release_date: "2019-07-25",
    developer: null,
  },
  {
    publisher: ["JOGARA LTD"],
    is_early_access: false,
    app_name: "Project Torque - Free 2 Play MMO Racing Game",
    steam_id: "1112400",
    vr_support: "not_supported",
    all_review_count: 1319,
    source: "steam",
    supported_os: ["win"],
    genre: ["Free to Play", "Massively Multiplayer", "Racing"],
    score: 0.5625,
    img_url:
      "https://cdn.akamai.steamstatic.com/steam/apps/1112400/header.jpg?t=1593034166",
    release_date: "2008-04-30",
    developer: ["Invictus Games Ltd.", "JOGARA LTD"],
  },
  {
    publisher: ["Afterthought Studios"],
    is_early_access: false,
    app_name: "CUPID - A free to play Visual Novel",
    steam_id: "421670",
    vr_support: "not_supported",
    all_review_count: 1201,
    source: "steam",
    supported_os: ["win", "mac"],
    genre: ["Free to Play", "Indie", "RPG", "Simulation"],
    score: 0.6,
    img_url:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/421670/header.jpg?t=1457099874",
    release_date: "2016-03-04",
    developer: ["Fervent"],
  },
  {
    publisher: ["Hook Games"],
    is_early_access: false,
    app_name: "Lines X Free",
    steam_id: "725340",
    vr_support: "not_supported",
    all_review_count: 1168,
    source: "steam",
    supported_os: ["win", "mac", "linux"],
    genre: ["Casual", "Free to Play", "Indie", "Strategy"],
    score: 0.6666666666666666,
    img_url:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/725340/header.jpg?t=1599559479",
    release_date: "2017-10-31",
    developer: ["Konstructors"],
  },
  {
    publisher: ["Fun Games For Free"],
    is_early_access: false,
    app_name: "Sniper 3D Assassin: Free to Play",
    steam_id: "922320",
    vr_support: "not_supported",
    all_review_count: 1132,
    source: "steam",
    supported_os: ["win", "mac"],
    genre: [
      "Action",
      "Adventure",
      "Casual",
      "Free to Play",
      "Indie",
      "RPG",
      "Simulation",
      "Strategy",
    ],
    score: 0.6,
    img_url:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/922320/header.jpg?t=1538576104",
    release_date: "2018-09-19",
    developer: ["Fun Games For Free"],
  },
  {
    publisher: [" 1C Entertainment"],
    is_early_access: false,
    app_name: "Ancestors Legacy Free Peasant Edition",
    steam_id: "720380",
    vr_support: "not_supported",
    all_review_count: 793,
    source: "steam",
    supported_os: ["win"],
    genre: ["Strategy"],
    score: 0.6,
    img_url:
      "https://cdn.akamai.steamstatic.com/steam/apps/720380/header.jpg?t=1617694482",
    release_date: "2018-02-06",
    developer: ["Destructive Creations"],
  },
  {
    publisher: ["Farsky Interactive"],
    is_early_access: false,
    app_name: "The Free Ones",
    steam_id: "670350",
    vr_support: "not_supported",
    all_review_count: 560,
    source: "steam",
    supported_os: ["win", "mac", "linux"],
    genre: ["Adventure"],
    score: 0.75,
    img_url:
      "https://cdn.akamai.steamstatic.com/steam/apps/670350/header.jpg?t=1536158770",
    release_date: "2018-07-12",
    developer: ["Farsky Interactive"],
  },
];

export default configData;
